language: node_js
node_js:
  - '7'
env:
  - CXX=g++-5.4
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5.4
before_script:
  - npm install
script:
  - npm run build:build